name: Trello Integration

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  trello:
    runs-on: ubuntu-latest
    environment: Trello
    steps:
      - name: Trello Card & GitHub PR Integration
        uses: rematocorp/trello-integration-action@v9.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-require-keyword-prefix: false
          github-enable-related-keyword-prefix: false
          github-require-trello-card: true
          github-include-pr-comments: false
          github-include-pr-commit-messages: true
          github-include-pr-branch-name: true
          github-allow-multiple-cards-in-pr-branch-name: false
          github-include-new-card-command: false
          github-create-new-card-on-merge: false
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-board-id: ${{ secrets.TRELLO_BOARD_ID }}
          trello-add-labels-to-cards: false
          trello-add-members-to-cards: false
          trello-switch-members-in-review: false
          trello-remove-unrelated-members: false
